### ISSUE TITLE
Ingestion of raw data

### ISSUE THREAD

**Issue by atlshearer** [CITS3200-2021-34/studious-telegram#3]
Currently the interfaces have no way to ingest the raw data. 

Likely it will make sense to have a seperate module that can ingest various raw formats and then pass the data to the question matcher. Including the data parsing in the question matcher will probably make it too bloated.

**Comment by FraserGilbert** [comment]
When you say "various raw formats" wouldn't they all be in text?

**Comment by atlshearer** [comment]
@FraserGilbert Yeah, they would all be text, specifically the email format. I'm just thinking that it would make sense for the processing to be kept fairly seperate to help readability/maintainability. 

That would also allow for different modules to be made for different formats. A module that might make sense could be a testing module that can be used to supply specific questions and answers in code.
